--属性相关
CDOTA_ATTRIBUTE_STRENGTH_ATTACK_DAMAGE = 1--每点力量提供攻击力
CDOTA_ATTRIBUTE_STRENGTH_HEALTH_REGEN = 0.05--每点力量提供生命恢复
CDOTA_ATTRIBUTE_INTELLIGENCE_SPELL_POWER = 1--每点智力提供1点法术强度
CDOTA_ATTRIBUTE_INTELLIGENCE_MANA = 20--每点智力提供魔法值--不再提供
CDOTA_ATTRIBUTE_INTELLIGENCE_MANA_REGEN = 0.7--每点智力提供魔法恢复
CDOTA_ATTRIBUTE_INTELLIGENCE_MAGICAL_CRIT_CHANCE = 0.1--每点智力提供魔法暴击
CDOTA_ATTRIBUTE_INTELLIGENCE_MAGICAL_ARMOR = 1--每点智力提供魔法抗性
CDOTA_ATTRIBUTE_AGILITY_PHYSICAL_CRIT_CHANCE = 0.1--每点敏捷提供物理暴击
CDOTA_ATTRIBUTE_AGILITY_PHYSICAL_ARMOR = 1--每点敏捷提供护甲
CDOTA_ATTRIBUTE_HEALTH_REGEN_NO_COMBAT = 7--战斗外百分比恢复速度
CDOTA_BASE_CRIT_DAMAGE = 100--基础暴击倍率
CDOTA_ATTRIBUTE_LEVEL_HEALTH = {
    ["death_knight"] = {20,5},
    ["mage"] = {20,5},
}

CDOTA_ATTRIBUTE_LEVEL_MANA_BASE_FACTOR = 20--每级增长的基础魔法值
CDOTA_ATTRIBUTE_LEVEL_MANA_INCREASE_FACTOR = 5--每级额外增长的魔法值

--技能相关
MAX_UNIT_LEVEL = 60
MIN_ABILITY_SLOT = 0
MAX_ABILITY_SLOT = 31

--伤害相关
ABILITY_DAMAGE_CALCULATE_TYPE_AP = 1
ABILITY_DAMAGE_CALCULATE_TYPE_SP = ABILITY_DAMAGE_CALCULATE_TYPE_AP * 2

--护甲
PHYSICAL_ARMOR_IGNORE_LEVEL_FACTOR = 10--每级等级差忽略的护甲(pct)
PHYSICAL_ARMOR_IGNORE_LEVEL_MAX = 10--忽略护甲时计算的最大等级差(pct)
--魔抗
MAGICAL_ARMOR_IGNORE_LEVEL_FACTOR = 10--每级等级差忽略的魔抗(pct)
MAGICAL_ARMOR_IGNORE_LEVEL_MAX = 10--忽略魔抗时计算的最大等级差(pct)