--属性相关
CDOTA_ATTRIBUTE_INTELLIGENCE_SPELL_POWER = 1--每点智力提供1点法术强度
CDOTA_ATTRIBUTE_INTELLIGENCE_MANA = 20--每点智力提供魔法值
CDOTA_BASE_CRIT_DAMAGE = 100--基础暴击倍率

--技能相关
MAX_UNIT_LEVEL = 60
MIN_ABILITY_SLOT = 0
MAX_ABILITY_SLOT = 18

--伤害相关
ABILITY_DAMAGE_CALCULATE_TYPE_AP = 1
ABILITY_DAMAGE_CALCULATE_TYPE_SP = ABILITY_DAMAGE_CALCULATE_TYPE_AP * 2